FROM node:21.6.1-bookworm-slim

WORKDIR /usr/src/app
RUN chown -R node:node /usr/src/app
USER node

COPY ./novelBuilder/package.json ./

RUN npm install

COPY ./novelBuilder .

EXPOSE 3000

CMD [ "npm", "run", "production" ]